Output demo1.gif
Set FontSize 14
Set Width 1200
Set Height 600

Hide
Type "export PS1='demo ~ $ '"
Enter

Type "alias scylla-reader='env VHS=1 TERM_PROGRAM= ../scylla-reader/target/release/scylla-reader'"
Enter

Ctrl+L
Show

Type "scylla-reader"
Enter
Sleep 2s

Type "i"
Sleep 500ms

Type "template"
Sleep 500ms
Enter
Sleep 500ms
Type "https://www.royalroad.com/fiction/117255/rend"
Sleep 500ms

Ctrl+S
Sleep 1s

Down
Sleep 1s

Enter
Sleep 2s
