Output demo2.gif
Set FontSize 16
Set Width 1200
Set Height 600

Hide
Type "export PS1='demo ~ $ '"
Enter

Type "alias scylla-reader='env VHS=1 TERM_PROGRAM= ../scylla-reader/target/release/scylla-reader'"
Enter

Type "scylla-reader"
Enter
Sleep 500ms

#Enter Book First time.
Down
Sleep 500ms
Type "2"

#Show Book
Show

Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Left
Sleep 1s
Left
Sleep 1s

Type "3"
Sleep 500ms
Down 2
Sleep 500ms
Enter
Sleep 1s
Type "2"
Sleep 500ms

Down@20ms 30
Sleep 1s
Up@20ms 40
Sleep 1s

