[package]
name = "scylla-reader"
version = "0.2.0"
edition = "2024"

[dependencies]
# TUI and Terminal Handling
ratatui = "0.29"
crossterm = "0.28"
# Network and Scraping
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Async
tokio = { version = "1.40", features = ["full"] }
curl = "0.4"

ratatui-image = { version = "3" }
image = "0.25"

rusqlite = { version = "0.32", features = ["bundled"] }
dirs = "5"


extism = "1"
scylla-plugin-api = { path = "../scylla-plugin-api" }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"

[features]
vhs-mode = []
